# Generated by Django 4.0 on 2021-12-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fieldmodel',
            new_name='Item',
        ),
    ]
